import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'kit drap simple',
      slug: 'kit-drap-simple',
      category: 'draps',
      image: '/images/parure.jpg',
      price: 17,
      brand: 'artisan blanchisseur',
      rating: 4.5,
      numReviews: 8,
      countInStock: 0,
      description:
        "kit comprenant un drap simple, une housse de couette 1 persone et une taie d'oreiller",
    },
    {
      name: 'kit drap double',
      slug: 'kit-drap-double',
      category: 'draps',
      image: '/images/parure.jpg',
      price: 17,
      brand: 'artisan blanchisseur',
      rating: 4.5,
      numReviews: 8,
      countInStock: 10,
      description:
        "kit comprenant un drap simple, une housse de couette 1 persone et une taie d'oreiller",
    },
    {
      name: 'kit drap simple & serviettes',
      slug: 'kit-drap-simple-serviettes',
      category: 'draps',
      image: '/images/parure.jpg',
      price: 21,
      brand: 'artisan blanchisseur',
      rating: 3.5,
      numReviews: 4,
      countInStock: 2,
      description:
        "kit comprenant un drap simple, une housse de couette 1 personne et une taie d'oreiller plus 2 serviettes par personne",
    },
    {
      name: 'kit drap double & serviettes',
      slug: 'kit-drap-double-serviettes',
      category: 'draps',
      image: '/images/parure.jpg',
      price: 21,
      brand: 'artisan blanchisseur',
      rating: 3.5,
      numReviews: 4,
      countInStock: 10,
      description:
        "kit comprenant un drap simple, une housse de couette 1 personne et une taie d'oreiller plus 2 serviettes par personne",
    },
    {
      name: 'kit serviettes',
      slug: 'kit-serviettes',
      category: 'serviette',
      image: '/images/parure.jpg',
      price: 9,
      brand: 'artisan blanchisseur',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'Le drap de bain Vidori est le plus moelleux et luxueux de notre gamme de linge éponge. Incroyablement confortable avec ses 700g/m², il est doux grâce à sa composition en coton majoritaire. Cette éponge présente un ourlet sergé, lui assurant sobriété et raffinement. ',
    },
    {
      name: 'Tapis de bain ',
      slug: 'Tapis-de-bain',
      category: 'serviettes',
      image: '/images/parure.jpg',
      price: 5,
      brand: 'artisan blanchisseur',
      rating: 3.5,
      numReviews: 4,
      countInStock: 10,
      description:
        "kit comprenant un drap double, une housse de couette 2 persones, 2 taies d'oreiller plus 2 serviettes par personne",
    },
    {
      name: 'Matelas suppléementaire pour lit parapluie ',
      slug: 'matelas-sup',
      category: 'accessoires',
      image: '/images/parure.jpg',
      price: 6,
      brand: 'artisan blanchisseur',
      rating: 3.5,
      numReviews: 2,
      countInStock: 10,
      description:
        "ATTENTION: Cet équipement ne peut pas être loué seul. Merci d'y associer un lit parapluie ou un autre matériel.Si vous trouvez que le matelas fourni dans le sac du lit parapluie est trop fin ou pas assez moëlleux pour votre bébé, ce matelas est à votre disposition.",
    },
    {
      name: 'Lit Parapluie ',
      slug: 'lit_parapluie',
      category: 'accessoires',
      image: '/images/parure.jpg',
      price: 24,
      brand: 'artisan blanchisseur',
      rating: 3.5,
      numReviews: 4,
      countInStock: 2,
      description:
        "Ce lit parapluie est un lit d'appoint pour les vacances. Facile à transporter dans son sac, il prend trop de place pour voyager en voiture ou dans le train. Nous actualisons régulièrement notre parc de lits parapluie et les couleurs et les marques de ces lits de bébé peuvent être différentes de la photo indiquée sur cette page. Nous choisissons toujours des couleurs neutres et des marques connues des parents. Pour ouvrir ce type de lit, il faut toujours maintenir le pied central le plus haut possible. Puis commencer par remonter les grands côtés et finir par les plus petits. Seulement alors, vous appuierez sur le pied central pour le bloquer.",
    },
    {
      name: 'Chaise Haute ',
      slug: 'chaise-haute',
      category: 'accessoires',
      image: '/images/parure.jpg',
      price: 24,
      brand: 'artisan blanchisseur',
      rating: 3.5,
      numReviews: 4,
      countInStock: 2,
      description:
        "Ce lit parapluie est un lit d'appoint pour les vacances. Facile à transporter dans son sac, il prend trop de place pour voyager en voiture ou dans le train. Nous actualisons régulièrement notre parc de lits parapluie et les couleurs et les marques de ces lits de bébé peuvent être différentes de la photo indiquée sur cette page. Nous choisissons toujours des couleurs neutres et des marques connues des parents. Pour ouvrir ce type de lit, il faut toujours maintenir le pied central le plus haut possible. Puis commencer par remonter les grands côtés et finir par les plus petits. Seulement alors, vous appuierez sur le pied central pour le bloquer.",
    },
  ],
  chalets: [
    {
      name: 'La Picherie',
      nameShort: 'La Picherie',
      slug: 'la_picherie_saint_nicolas',
      category: 'chalet',
      village: 'Saint Nicolas de Véroce',
      image_2: '/images/picherie_haut/picherie_haut_1.webp',
      image_1: '/images/picherie_haut/picherie_haut_2.webp',
      image_3: '/images/picherie_haut/picherie_haut_3.webp',
      image_4: '/images/picherie_haut/picherie_haut_4.webp',
      image_5: '/images/picherie_haut/picherie_haut_5.webp',
      airbnb: 'https://airbnb.com/h/lapicherie',
      private: 'https://www.appchaletmontjoye.conciergerie-saint-gervais.com/',
      booking: '',
      bedrooms: 4,
      capacity: 18,
      sauna: '1 sauna',
      jacuzzy: '',
      hammam: '',
      firePlace: '1 cheminée',
      carPark: '4 places de parking',
      busTopName: 'arrêt de bus Lachat',
      kitchenSize: '60 m2',
      bathtube: 1,
      dryer: '1 seche linge',
      dishwasher: '1 lave vaisselle',
      tvscreen: '1 television',
      party: 0,
      conciergerie: 'Conciergerie St Gervais 06 07 85 90 58',
      foldingBed: '1 lit parapluie',
      highChair: '1 chaise haute',
      vueOn: 'massif du Mont Blanc, les fiz & les Aravis',
      wifi: true,
      sdb: 5,
      surface: 140,
      adresse: '147 Chem. du Thovex, 74170 Saint-Gervais-les-Bains, France',
      description:
        'Bienvenus dans cette splendide ferme de 1842 fraichement rénovée avec des prestations haut de gamme, Navette au pied de la ferme pour accès au télésiège des Chattrix à 1km, et au village de St Nicolas ou St Gervais, Proche du village authentique de Saint Nicolas de Véroce, vue : Mont Blanc, chaîne des Fix, une partie des Aravis et forêt.Séjour avec cheminée, cuisine et salle à manger de 100m2. 4 chambres doubles, 1 avec canapé lit, 2 dortoirs, 5 SDB.Terrasse couverte et jardin',
      quartier:
        'Accès aux chemins de randonnée directement.Départ depuis la ferme en ski de randonnée.Espace Evasion/Mont blanc pour le ski de piste (St Nicolas de Veroce, St Gervais, Megeve). Navette au pied de la ferme (Arrêt les Vincents) pour accéder au télésiège des chattrix à 1km ou aux villages de St Nicolas ou St Gervais.',
    },
    {
      name: 'Le Bas de la Picherie',
      nameShort: 'Le bas de la Picherie',
      slug: 'la_picherie_bas_saint_nicolas',
      category: 'appartement',
      village: 'Saint Nicolas de Véroce',
      image_1: '/images/picherie_bas/picherie_bas_1.webp',
      image_2: '/images/picherie_bas/picherie_bas_2.webp',
      image_3: '/images/picherie_bas/picherie_bas_3.webp',
      image_4: '/images/picherie_bas/picherie_bas_4.webp',
      image_5: '/images/picherie_bas/picherie_bas_5.webp',
      airbnb: 'https://airbnb.com/h/lapicherie',
      private: 'https://www.appchaletmontjoye.conciergerie-saint-gervais.com/',
      booking: '',
      bedrooms: '4 chambres',
      capacity: 10,
      sauna: 0,
      jacuzzy: 0,
      stowart: '1 stöwart',
      hammam: 0,
      firePlace: '1 cheminée',
      carPark: '4 places de parking',
      busTopName: 'arrêt de bus Lachat',
      kitchenSize: 'surface cuisine 60 m2',
      bathtube: 1,
      shower: 3,
      dryer: '1 seche linge',
      whashingMachine: '1 machine à laver',
      dishwasher: '1 lave vaisselle',
      tvscreen: '1 television',
      party: 'soirée non autorisée',
      conciergerie: 'Conciergerie St Gervais 06 07 85 90 58',
      foldingBed: 'sur réservation',
      highChair: 'sur réservation   ',
      vueOn: 'massif du Mont Blanc, les fiz & les Aravis',
      wifi: 'wifi gratuit',
      sdb: 4,
      surface: 140,
      adresse: '147 Chem. du Thovex, 74170 Saint-Gervais-les-Bains, France',
      description:
        'Demi-ferme de 14O m2, vue : Mont Blanc, Chaine des Fiz, Aravis et forêt. Domaine skiable Evasion/Mont Blanc ; Navette au pied de la ferme pour accès au télésiège des Chattrix (1km) et village de St Nicolas ou St Gervais. Grand séjour avec poële à bois, cuisine de 60 m2. 3 chambres doubles en suite avec salles d eau. 1 dortoir de 4 lits simples avec salle de bains (baignoire). Chauffe chaussures dans local à ski. Jardin.',
      quartier:
        'Accès aux chemins de randonnée directement.Départ depuis la ferme en ski de randonnée.Espace Evasion/Mont blanc pour le ski de piste (St Nicolas de Veroce, St Gervais, Megeve). Navette au pied de la ferme (Arrêt les Vincents) pour accéder au télésiège des chattrix à 1km ou aux villages de St Nicolas ou St Gervais.',
    },
    {
      name: 'La Pieuca',
      nameShort: 'La Pieuca',
      slug: 'la_pieuca',
      category: 'chalet',
      village: 'Les contamines montjoie',
      image_1: '/images/pieuca/la_pieuca_1.webp',
      image_2: '/images/pieuca/la_pieuca_2.webp',
      image_3: '/images/pieuca/la_pieuca_3.webp',
      image_4: '/images/pieuca/la_pieuca_4.webp',
      image_5: '/images/pieuca/la_pieuca_5.webp',
      airbnb: 'https://airbnb.com/h/lapicherie',
      private: 'https://www.appchaletmontjoye.conciergerie-saint-gervais.com/',
      booking: '',
      bedrooms: '4 chambres',
      capacity: 12,
      sauna: 0,
      jacuzzy: 0,
      stowart: 0,
      hammam: 0,
      firePlace: '1 cheminée',
      carPark: '4 places de parking',
      busTopName: 'arrêt de bus Lachat',
      kitchenSize: 'surface cuisine 60 m2',
      bathtube: 2,
      shower: 1,
      dryer: '1 seche linge',
      whashingMachine: '1 machine à laver',
      dishwasher: '1 lave vaisselle',
      tvscreen: '1 television',
      party: 'soirée non autorisée',
      conciergerie: 'Conciergerie St Gervais 06 07 85 90 58',
      foldingBed: 'sur réservation',
      highChair: 'sur réservation',
      vueOn: 'massif du Mont Blanc, les fiz & les Aravis',
      wifi: 'wifi gratuit',
      sdb: 5,
      surface: 140,
      adresse: '147 Chem. du Thovex, 74170 Saint-Gervais-les-Bains, France',
      description:
        'Bienvenus dans cette splendide ferme de 1842 fraichement rénovée avec des prestations haut de gamme, Navette au pied de la ferme pour accès au télésiège des Chattrix à 1km, et au village de St Nicolas ou St Gervais, Proche du village authentique de Saint Nicolas de Véroce, vue : Mont Blanc, chaîne des Fix, une partie des Aravis et forêt.Séjour avec cheminée, cuisine et salle à manger de 100m2. 4 chambres doubles, 1 avec canapé lit, 2 dortoirs, 5 SDB.Terrasse couverte et jardin',
      quartier:
        'Accès aux chemins de randonnée directement.Départ depuis la ferme en ski de randonnée.Espace Evasion/Mont blanc pour le ski de piste (St Nicolas de Veroce, St Gervais, Megeve). Navette au pied de la ferme (Arrêt les Vincents) pour accéder au télésiège des chattrix à 1km ou aux villages de St Nicolas ou St Gervais.',
    },
    {
      name: 'Chalet luxe & calme La Chandelle, 6-12 p, Vue+++',
      nameShort: 'La chandelle',
      slug: 'la_chandelle',
      category: 'chalet',
      village: 'Saint Gervais les Bains',
      image_1: '/images/la_chandelle/la_chandelle_1.webp',
      image_2: '/images/la_chandelle/la_chandelle_2.webp',
      image_3: '/images/la_chandelle/la_chandelle_3.webp',
      image_4: '/images/la_chandelle/la_chandelle_5.webp',
      image_5: '/images/la_chandelle/la_chandelle_4.webp',
      airbnb: 'https://airbnb.com/h/lachandelle',
      private: 'https://www.appchaletmontjoye.conciergerie-saint-gervais.com/',
      booking: '',
      bedrooms: '4 chambres',
      capacity: 12,
      sauna: 0,
      jacuzzy: 0,
      stowart: '1 stöwart',
      hammam: 0,
      firePlace: '1 cheminée',
      carPark: '4 places de parking',
      busTopName: 'arrêt de bus Lachat',
      kitchenSize: 'surface cuisine 60 m2',
      bathtube: 1,
      shower: 3,
      dryer: '1 seche linge',
      whashingMachine: '1 machine à laver',
      dishwasher: '1 lave vaisselle',
      tvscreen: 0,
      party: 'soirée non autorisée',
      conciergerie: 'Conciergerie St Gervais 06 07 85 90 58',
      foldingBed: 'sur réservation',
      highChair: 'sur réservation',
      vueOn: 'massif du Mont Blanc, les fiz & les Aravis',
      wifi: 'wifi gratuit',
      sdb: 4,
      surface: 140,
      adresse: '147 Chem. du Thovex, 74170 Saint-Gervais-les-Bains, France',
      description:
        'Calme absolu à Bionnassay (alt. 1400 m), sur le GR Tour du Mont Blanc, avec une vue imprenable sur le mont Vorassay et laiguille du Gouter. Cosy, élégant et chaleureux. Réhabilité par un architecte en 2021 dans le respect des matériaux du pays (vieux bois, pierre, ardoise). Expérience d immersion ht montagne, à seulement 15 mn de St Gervais, de ses commodités & domaines skiables. 4X4 à disposition (obligatoire l hiver). Idéal vacances sportives (rando, raquettes) ou télétravail en pleine nature.',
      quartier:
        'Accès aux chemins de randonnée directement.Départ depuis la ferme en ski de randonnée.Espace Evasion/Mont blanc pour le ski de piste (St Nicolas de Veroce, St Gervais, Megeve). Navette au pied de la ferme (Arrêt les Vincents) pour accéder au télésiège des chattrix à 1km ou aux villages de St Nicolas ou St Gervais.',
    },
    {
      name: 'Appartement Chalet MontJoy',
      nameShort: 'Appartement Chalet MontJoy',
      slug: 'appartement_chalet_montjoy',
      category: 'chalet',
      village: 'Saint Nicolas de Véroce',
      image_2: '/images/leslie/leslie_2.webp',
      image_3: '/images/leslie/leslie_3.webp',
      image_1: '/images/leslie/leslie_1.webp',
      image_4: '/images/leslie/leslie_5.webp',
      image_5: '/images/leslie/leslie_4.webp',
      airbnb: 'https://airbnb.com/h/lachandelle',
      private: 'https://www.appchaletmontjoye.conciergerie-saint-gervais.com/',
      booking: '',
      bedrooms: '1 chambre',
      capacity: 4,
      sauna: 0,
      jacuzzy: 0,
      stowart: 0,
      hammam: 0,
      firePlace: 0,
      carPark: 0,
      busTopName: 0,
      kitchenSize: 0,
      bathtube: 1,
      shower: 0,
      dryer: 0,
      whashingMachine: '1 machine à laver',
      dishwasher: '1 lave vaisselle',
      tvscreen: 1,
      party: 'soirée non autorisée',
      conciergerie: 'Conciergerie St Gervais 06 07 85 90 58',
      foldingBed: 'sur réservation',
      highChair: 'sur réservation',
      vueOn: 'massif du Mont Blanc',
      wifi: 'wifi gratuit',
      sdb: 1,
      surface: 37,
      adresse: 'route de saint nicolas, 74170 Saint-Gervais-les-Bains, France',
      description:
        'Calme absolu à Bionnassay (alt. 1400 m), sur le GR Tour du Mont Blanc, avec une vue imprenable sur le mont Vorassay et laiguille du Gouter. Cosy, élégant et chaleureux. Réhabilité par un architecte en 2021 dans le respect des matériaux du pays (vieux bois, pierre, ardoise). Expérience d immersion ht montagne, à seulement 15 mn de St Gervais, de ses commodités & domaines skiables. 4X4 à disposition (obligatoire l hiver). Idéal vacances sportives (rando, raquettes) ou télétravail en pleine nature.',
      quartier:
        'Accès aux chemins de randonnée directement.Départ depuis la ferme en ski de randonnée.Espace Evasion/Mont blanc pour le ski de piste (St Nicolas de Veroce, St Gervais, Megeve). Navette au pied de la ferme (Arrêt les Vincents) pour accéder au télésiège des chattrix à 1km ou aux villages de St Nicolas ou St Gervais.',
    },
    {
      name: 'Chalet au cœur de St-Gervais, vue sur le Mont Joly',
      nameShort: 'Chalet au cœur de St-Gervais',
      slug: 'chalet_saint_gervais',
      category: 'appartement',
      village: 'Saint Gervais les Bains',
      image_2: '/images/valentin/valentin_11.webp',
      image_3: '/images/valentin/valentin_3.webp',
      image_1: '/images/valentin/valentin_12.webp',
      image_4: '/images/valentin/valentin_5.webp',
      image_5: '/images/valentin/valentin_4.webp',
      airbnb: 'https://airbnb.com/h/lachandelle',
      private: 'https://www.appchaletmontjoye.conciergerie-saint-gervais.com/',
      booking: '',
      bedrooms: '4 chambres',
      capacity: 12,
      sauna: 0,
      jacuzzy: 1,
      stowart: 0,
      hammam: 0,
      firePlace: '1 cheminée',
      carPark: '2 places de parking',
      busTopName: 0,
      kitchenSize: 'surface cuisine 10 m2',
      bathtube: 1,
      shower: 2,
      dryer: '1 seche linge',
      whashingMachine: '1 machine à laver',
      dishwasher: '1 lave vaisselle',
      tvscreen: 1,
      party: 'soirée non autorisée',
      conciergerie: 'Conciergerie St Gervais 06 07 85 90 58',
      foldingBed: 'sur réservation',
      highChair: 'sur réservation',
      vueOn: 'Mont Joly',
      wifi: 'wifi gratuit',
      sdb: 2,
      surface: 120,
      adresse: '38 Chem. de l Usine, 74170 Saint-Gervais-les-Bains, France',
      description:
        'Nous vous proposons de séjourner dans notre chalet familial idéalement situé, au calme, mais proche du centre de Saint-Gervais, avec jacuzzi et une vue imprenable sur le Mont Joly et les Dômes de Miage. Entièrement rénové et aménagé avec élégance, le chalet est composé de bois clair et de pierres, pour une atmosphère conviviale et chaleureuse. La pièce de vie très lumineuse suggère de belles soirées au coin du feu. La terrasse exposée plein sud permettra de profiter de chaque rayon de soleil.',
      quartier: '',
    },
    {
      name: 'T3 - 60 m2 - TELECABINES à 50 m - SKI IN - SKI OUT',
      nameShort: 'T3 - 60 m2 - TELECABINES à 50 m',
      slug: 'appartement_t3_60_m2',
      category: 'appartement',
      village: 'Saint Gervais les Bains',
      image_2: '/images/muller/t3/t3_1.webp',
      image_3: '/images/muller/t3/t3_3.webp',
      image_1: '/images/muller/t3/t3_2.webp',
      image_4: '/images/muller/t3/t3_4.webp',
      image_5: '/images/muller/t3/t3_5.webp',
      airbnb: 'https://airbnb.com/h/t3famillefrancoismuler',
      private: 'https://www.appchaletmontjoye.conciergerie-saint-gervais.com/',
      booking: '',
      bedrooms: '2 chambres',
      capacity: 4,
      sauna: 0,
      jacuzzy: 0,
      stowart: 0,
      hammam: 0,
      firePlace: 0,
      carPark: '1 place de parking',
      busTopName: 0,
      kitchenSize: 'surface cuisine 5 m2',
      bathtube: 1,
      shower: 0,
      dryer: '1 seche linge',
      whashingMachine: '1 machine à laver',
      dishwasher: '1 lave vaisselle',
      tvscreen: 0,
      party: 'soirée non autorisée',
      conciergerie: 'Conciergerie St Gervais 06 07 85 90 58',
      foldingBed: 'sur réservation',
      highChair: 'sur réservation',
      vueOn: 'Les Aravis',
      wifi: 'wifi gratuit',
      sdb: 1,
      surface: 60,
      adresse: '119 Chem. des Prés, 74170 Saint-Gervais-les-Bains, France',
      description:
        'Bel appartement neuf décoré avec soin à proximité des remontées mécaniques et des commerces.Situé au 2ème étage d un immeuble sécurisé avec ascenseur.',
      quartier:
        'Il se compose d une pièce principale équipée d une télévision et d une connexion wi-fi gratuite,  d une cuisine entièrement équipée, d une chambre avec un lit king size, une chambre avec 2 lits, d une salle de bain avec baignoire, des WC séparés. Il dispose également d une terrasse d environ 7m² avec vue sur les aiguilles de Warens. Un garage individuel en sous-sol complète le bien.',
    },
  ],
};

export default data;
